post http://localhost:3001/api/patients/d2773336-f723-11e9-8f0b-362b9e155667/entries
Content-Type: application/json

{
"date": "2022-10-20",
"specialist": "Dr Future",
"type": "HealthCheck",
"description": "Yearly control visit. Nanites injection.",
"healthCheckRating": 0
}